// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: HomeUI

#ifndef _HOMEUI_UI_H
#define _HOMEUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_DimmerSlider(lv_event_t * e);
extern lv_obj_t * ui_DimmerSlider;
extern lv_obj_t * ui_LightsOnSwitch;
extern lv_obj_t * ui_LightsOnLabel;
extern lv_obj_t * ui_LightsHeading;
extern lv_obj_t * ui_WaekupTimeSelect;
extern lv_obj_t * ui_WakeupSetLabel;
extern lv_obj_t * ui_WakeupSetButton;
extern lv_obj_t * ui_DimmerPct;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_SetWakeupBtnLabel;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
