// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: HomeUI

#include "ui.h"

void dimmerChanged(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	lv_obj_t * target = lv_event_get_target(e);
	char buf[8];
	auto dimmerValue = lv_slider_get_value(target);
	lv_snprintf(buf, sizeof buf, "%d%%", dimmerValue);
	if(event_code == LV_EVENT_RELEASED) {
		_ui_label_set_property(ui_DimmerPct, _UI_LABEL_PROPERTY_TEXT, buf);
		if (dimmerValue > 0) {
			lv_obj_add_state(ui_LightsOnSwitch, LV_STATE_CHECKED);
		} else {
			lv_obj_clear_state(ui_LightsOnSwitch, LV_STATE_CHECKED);
		}
	}
}

void LightSwitchCallback(lv_event_t * e)
{
	// Your code here
	lv_obj_t * target = lv_event_get_target(e);

}

void SetWakeupCallback(lv_event_t * e)
{
	// Your code here
}
