// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: HomeUI

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DimmerSlider = lv_slider_create(ui_Screen1);
    lv_slider_set_value(ui_DimmerSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_DimmerSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_DimmerSlider, 1,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_DimmerSlider, 50);
    lv_obj_set_height(ui_DimmerSlider, 278);
    lv_obj_set_x(ui_DimmerSlider, 278);
    lv_obj_set_y(ui_DimmerSlider, 37);
    lv_obj_set_align(ui_DimmerSlider, LV_ALIGN_CENTER);


    ui_LightsOnSwitch = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_LightsOnSwitch, 195);
    lv_obj_set_height(ui_LightsOnSwitch, 109);
    lv_obj_set_x(ui_LightsOnSwitch, -34);
    lv_obj_set_y(ui_LightsOnSwitch, -76);
    lv_obj_set_align(ui_LightsOnSwitch, LV_ALIGN_CENTER);


    ui_LightsOnLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LightsOnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightsOnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightsOnLabel, -272);
    lv_obj_set_y(ui_LightsOnLabel, -76);
    lv_obj_set_align(ui_LightsOnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightsOnLabel, "Lights On/Off");
    lv_obj_set_style_text_font(ui_LightsOnLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightsHeading = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LightsHeading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightsHeading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightsHeading, -44);
    lv_obj_set_y(ui_LightsHeading, -193);
    lv_obj_set_align(ui_LightsHeading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightsHeading, "Lights Control");
    lv_obj_set_style_text_font(ui_LightsHeading, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WaekupTimeSelect = lv_spinbox_create(ui_Screen1);
    lv_obj_set_width(ui_WaekupTimeSelect, 146);
    lv_obj_set_height(ui_WaekupTimeSelect, 70);
    lv_obj_set_x(ui_WaekupTimeSelect, -97);
    lv_obj_set_y(ui_WaekupTimeSelect, 77);
    lv_obj_set_align(ui_WaekupTimeSelect, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_WaekupTimeSelect, 4, 2);
    lv_spinbox_set_range(ui_WaekupTimeSelect, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_WaekupTimeSelect, 1 - 1);
    lv_spinbox_set_value(ui_WaekupTimeSelect, 630);
    lv_obj_set_style_text_font(ui_WaekupTimeSelect, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WakeupSetLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WakeupSetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WakeupSetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WakeupSetLabel, -288);
    lv_obj_set_y(ui_WakeupSetLabel, 78);
    lv_obj_set_align(ui_WakeupSetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WakeupSetLabel, "Set wakeup override \nfor tomorrow");
    lv_obj_set_style_text_align(ui_WakeupSetLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WakeupSetButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_WakeupSetButton, 87);
    lv_obj_set_height(ui_WakeupSetButton, 70);
    lv_obj_set_x(ui_WakeupSetButton, 53);
    lv_obj_set_y(ui_WakeupSetButton, 79);
    lv_obj_set_align(ui_WakeupSetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WakeupSetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WakeupSetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DimmerPct = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_DimmerPct, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DimmerPct, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DimmerPct, 277);
    lv_obj_set_y(ui_DimmerPct, -131);
    lv_obj_set_align(ui_DimmerPct, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DimmerPct, "0%");

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);

    ui_SetWakeupBtnLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SetWakeupBtnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetWakeupBtnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetWakeupBtnLabel, 50);
    lv_obj_set_y(ui_SetWakeupBtnLabel, 79);
    lv_obj_set_align(ui_SetWakeupBtnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetWakeupBtnLabel, "Set");

    lv_obj_add_event_cb(ui_DimmerSlider, ui_event_DimmerSlider, LV_EVENT_ALL, NULL);

}
