// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_TabClock;
lv_obj_t * ui_Clock;
lv_obj_t * ui_WakeupCountdown;
lv_obj_t * ui_TabTV;
lv_obj_t * ui_PlaylstSelection;
void ui_event_ButtonPlaylistUp(lv_event_t * e);
lv_obj_t * ui_ButtonPlaylistUp;
lv_obj_t * ui_PlaylistUpLabel;
void ui_event_ButtonPlaylistDown(lv_event_t * e);
lv_obj_t * ui_ButtonPlaylistDown;
lv_obj_t * ui_PlaylistDownLabel;
void ui_event_ButtonPlaylistSelect(lv_event_t * e);
lv_obj_t * ui_ButtonPlaylistSelect;
lv_obj_t * ui_PlaylistSelectLabel;
void ui_event_SkipAhead(lv_event_t * e);
lv_obj_t * ui_SkipAhead;
lv_obj_t * ui_SkipAheadLabel;
void ui_event_PlayPauseButton(lv_event_t * e);
lv_obj_t * ui_PlayPauseButton;
lv_obj_t * ui_PlayPauseLabel;
lv_obj_t * ui_PlaylistIdDisplay;
lv_obj_t * ui_TabLights;
void ui_event_LightsDimmer(lv_event_t * e);
lv_obj_t * ui_LightsDimmer;
lv_obj_t * ui_LabelDimmerPct;
lv_obj_t * ui_LabelWakeupTime;
lv_obj_t * ui_KeyboardWakeup;
lv_obj_t * ui_WakeupTimeSpinbox;
void ui_event_SetWakeup(lv_event_t * e);
lv_obj_t * ui_SetWakeup;
lv_obj_t * ui_LabelSubmitWakeup;
void ui_event_LightSwitch(lv_event_t * e);
lv_obj_t * ui_LightSwitch;
lv_obj_t * ui_LabelLights;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ButtonPlaylistUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ScrollPlaylistUp(e);
    }
}
void ui_event_ButtonPlaylistDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ScrollPlaylistDown(e);
    }
}
void ui_event_ButtonPlaylistSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        NewPlaylistSelected(e);
    }
}
void ui_event_SkipAhead(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        TvSkipForward(e);
    }
}
void ui_event_PlayPauseButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        TvPauseAction(e);
    }
}
void ui_event_LightsDimmer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        DimmerUpdated(e);
    }
}
void ui_event_SetWakeup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        SetWakeupTime(e);
    }
}
void ui_event_LightSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ToggleLightSwitch(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
