// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: UI

// #include <widgets/roller/lv_roller.h>

// #include <core/lv_obj_event.h>

#include "ui.h"

void ScrollPlaylistUp(lv_event_t * e)
{
	char c = LV_KEY_UP;
	lv_event_send(ui_PlaylstSelection, LV_EVENT_KEY, &c);
	char buf[40] = "";
	lv_roller_get_selected_str(ui_PlaylstSelection, buf, 40);
	lv_label_set_text_fmt(ui_PlaylistIdDisplay, "%u: %s", lv_roller_get_selected(ui_PlaylstSelection), buf);
}

void ScrollPlaylistDown(lv_event_t * e)
{
	char c = LV_KEY_DOWN;
	lv_event_send(ui_PlaylstSelection, LV_EVENT_KEY, &c);
	char buf[40] = "";
	lv_roller_get_selected_str(ui_PlaylstSelection, buf, 40);
	lv_label_set_text_fmt(ui_PlaylistIdDisplay, "%u: %s", lv_roller_get_selected(ui_PlaylstSelection), buf);
}

extern volatile bool change_playlist_requested;
void NewPlaylistSelected(lv_event_t * e)
{
	change_playlist_requested = true;
}

extern volatile bool change_lights_requested;
void DimmerUpdated(lv_event_t * e)
{
	const auto dimmer = lv_slider_get_value(ui_LightsDimmer);
	lv_label_set_text_fmt(ui_LabelDimmerPct, "%d%%", dimmer);
	if (dimmer == 0) {
		lv_obj_clear_state(ui_LightSwitch, LV_STATE_CHECKED);
	} else {
		lv_obj_add_state(ui_LightSwitch, LV_STATE_CHECKED);
	}
	// Trigger an update to the lights via MQTT
	change_lights_requested = true;
}

void SetWakeupTime(lv_event_t * e)
{
	// Your code here
}

void ToggleLightSwitch(lv_event_t * e)
{
	if (lv_obj_has_state(ui_LightSwitch, LV_STATE_CHECKED)) {
		lv_slider_set_value(ui_LightsDimmer, 100, LV_ANIM_ON);
	} else {
		lv_slider_set_value(ui_LightsDimmer, 0, LV_ANIM_ON);
	}
	// Trigger an update to the lights via MQTT
	change_lights_requested = true;
}

void TvSkipForward(lv_event_t * e)
{
	// Your code here
}

void TvPauseAction(lv_event_t * e)
{
	// Your code here
}
