// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"

void ScrollPlaylistUp(lv_event_t * e)
{
	// Your code here
}

void ScrollPlaylistDown(lv_event_t * e)
{
	// Your code here
}

void NewPlaylistSelected(lv_event_t * e)
{
	// Your code here
}

void DimmerUpdated(lv_event_t * e)
{
	// Your code here
}

void SetWakeupTime(lv_event_t * e)
{
	// Your code here
}

void ToggleLightSwitch(lv_event_t * e)
{
	// Your code here
}
