// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: UI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ScrollPlaylistUp(lv_event_t * e);
void ScrollPlaylistDown(lv_event_t * e);
void NewPlaylistSelected(lv_event_t * e);
void DimmerUpdated(lv_event_t * e);
void SetWakeupTime(lv_event_t * e);
void ToggleLightSwitch(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
