// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: TabbedHomeUI

#ifndef _TABBEDHOMEUI_UI_H
#define _TABBEDHOMEUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabLights;
extern lv_obj_t * ui_LightsHeader;
extern lv_obj_t * ui_LightsOnLabel;
void ui_event_LightsOnSwitch(lv_event_t * e);
extern lv_obj_t * ui_LightsOnSwitch;
void ui_event_LightsDimmerSlider(lv_event_t * e);
extern lv_obj_t * ui_LightsDimmerSlider;
extern lv_obj_t * ui_WakeupTimeRoller;
extern lv_obj_t * ui_DimmerValueLabel;
void ui_event_WakeupOverrideButton(lv_event_t * e);
extern lv_obj_t * ui_WakeupOverrideButton;
extern lv_obj_t * ui_lblWakeupSubmit;
extern lv_obj_t * ui_TabTV;
extern lv_obj_t * ui_TVControlHeading;
void ui_event_TvPowerSwitch(lv_event_t * e);
extern lv_obj_t * ui_TvPowerSwitch;
extern lv_obj_t * ui_PlaylistSelectRoller;
void ui_event_TvVolumeSlider(lv_event_t * e);
extern lv_obj_t * ui_TvVolumeSlider;
void ui_event_PlaylistUp(lv_event_t * e);
extern lv_obj_t * ui_PlaylistUp;
extern lv_obj_t * ui_lblPlaylistUp;
void ui_event_SelectPlaylistButton(lv_event_t * e);
extern lv_obj_t * ui_SelectPlaylistButton;
void ui_event_PlaylistDown(lv_event_t * e);
extern lv_obj_t * ui_PlaylistDown;
extern lv_obj_t * ui_lblPlaylistDown;
extern lv_obj_t * ui_lblSelectPlaylist;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
