// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: TabbedHomeUI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void LightsOnCallback(lv_event_t * e);
void DimmerChangedCallback(lv_event_t * e);
void WakeupOverrideCallback(lv_event_t * e);
void startWakeupNow(lv_event_t * e);
void TvPowerToggleCallback(lv_event_t * e);
void TvVolumeChangeCallback(lv_event_t * e);
void playlistUpCallback(lv_event_t * e);
void playlistSubmitCallback(lv_event_t * e);
void playlistDownCallback(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
