// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: TabbedHomeUI

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_BOTTOM, 50);
    lv_obj_set_width(ui_TabView1, 800);
    lv_obj_set_height(ui_TabView1, 480);
    lv_obj_set_x(ui_TabView1, 1);
    lv_obj_set_y(ui_TabView1, 0);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_TabLights = lv_tabview_add_tab(ui_TabView1, "Lights");

    ui_LightsHeader = lv_label_create(ui_TabLights);
    lv_obj_set_width(ui_LightsHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightsHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightsHeader, -28);
    lv_obj_set_y(ui_LightsHeader, -158);
    lv_obj_set_align(ui_LightsHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightsHeader, "Lights Control");
    lv_obj_set_style_text_font(ui_LightsHeader, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightsOnLabel = lv_label_create(ui_TabLights);
    lv_obj_set_width(ui_LightsOnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightsOnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightsOnLabel, -265);
    lv_obj_set_y(ui_LightsOnLabel, -75);
    lv_obj_set_align(ui_LightsOnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightsOnLabel, "On/Off");
    lv_obj_set_style_text_font(ui_LightsOnLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightsOnSwitch = lv_switch_create(ui_TabLights);
    lv_obj_set_width(ui_LightsOnSwitch, 149);
    lv_obj_set_height(ui_LightsOnSwitch, 74);
    lv_obj_set_x(ui_LightsOnSwitch, -80);
    lv_obj_set_y(ui_LightsOnSwitch, -69);
    lv_obj_set_align(ui_LightsOnSwitch, LV_ALIGN_CENTER);


    ui_LightsDimmerSlider = lv_slider_create(ui_TabLights);
    lv_slider_set_value(ui_LightsDimmerSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_LightsDimmerSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_LightsDimmerSlider, 0,
                                                                                                       LV_ANIM_OFF);
    lv_obj_set_width(ui_LightsDimmerSlider, 47);
    lv_obj_set_height(ui_LightsDimmerSlider, 272);
    lv_obj_set_x(ui_LightsDimmerSlider, 327);
    lv_obj_set_y(ui_LightsDimmerSlider, 9);
    lv_obj_set_align(ui_LightsDimmerSlider, LV_ALIGN_CENTER);


    ui_WakeupTimeRoller = lv_roller_create(ui_TabLights);
    lv_roller_set_options(ui_WakeupTimeRoller, "4:00\n4:30\n5:00\n5:30\n6:00\n6:30\n7:00\n7:30\n8:00\n8:30",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_WakeupTimeRoller, 4, LV_ANIM_OFF);
    lv_obj_set_height(ui_WakeupTimeRoller, 139);
    lv_obj_set_width(ui_WakeupTimeRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_WakeupTimeRoller, -274);
    lv_obj_set_y(ui_WakeupTimeRoller, 63);
    lv_obj_set_align(ui_WakeupTimeRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_WakeupTimeRoller, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DimmerValueLabel = lv_label_create(ui_TabLights);
    lv_obj_set_width(ui_DimmerValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DimmerValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DimmerValueLabel, 325);
    lv_obj_set_y(ui_DimmerValueLabel, -171);
    lv_obj_set_align(ui_DimmerValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DimmerValueLabel, "0%");

    ui_WakeupOverrideButton = lv_btn_create(ui_TabLights);
    lv_obj_set_width(ui_WakeupOverrideButton, 100);
    lv_obj_set_height(ui_WakeupOverrideButton, 103);
    lv_obj_set_x(ui_WakeupOverrideButton, -166);
    lv_obj_set_y(ui_WakeupOverrideButton, 60);
    lv_obj_set_align(ui_WakeupOverrideButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WakeupOverrideButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WakeupOverrideButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblWakeupSubmit = lv_label_create(ui_TabLights);
    lv_obj_set_width(ui_lblWakeupSubmit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWakeupSubmit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWakeupSubmit, -166);
    lv_obj_set_y(ui_lblWakeupSubmit, 62);
    lv_obj_set_align(ui_lblWakeupSubmit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWakeupSubmit, "Override\nWakeup\n   Time");
    lv_obj_set_style_text_font(ui_lblWakeupSubmit, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabTV = lv_tabview_add_tab(ui_TabView1, "TV");

    ui_TVControlHeading = lv_label_create(ui_TabTV);
    lv_obj_set_width(ui_TVControlHeading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TVControlHeading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TVControlHeading, -183);
    lv_obj_set_y(ui_TVControlHeading, -160);
    lv_obj_set_align(ui_TVControlHeading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TVControlHeading, "TV Controls");
    lv_obj_set_style_text_font(ui_TVControlHeading, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TvPowerSwitch = lv_switch_create(ui_TabTV);
    lv_obj_set_width(ui_TvPowerSwitch, 125);
    lv_obj_set_height(ui_TvPowerSwitch, 69);
    lv_obj_set_x(ui_TvPowerSwitch, 71);
    lv_obj_set_y(ui_TvPowerSwitch, -157);
    lv_obj_set_align(ui_TvPowerSwitch, LV_ALIGN_CENTER);


    ui_PlaylistSelectRoller = lv_roller_create(ui_TabTV);
    lv_roller_set_options(ui_PlaylistSelectRoller, "Father Ted\nFuturama	\nThe Simpsons\nAre You Being Served?\nRandom All",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_PlaylistSelectRoller, 1, LV_ANIM_OFF);
    lv_obj_set_width(ui_PlaylistSelectRoller, 395);
    lv_obj_set_height(ui_PlaylistSelectRoller, 207);
    lv_obj_set_x(ui_PlaylistSelectRoller, -9);
    lv_obj_set_y(ui_PlaylistSelectRoller, 43);
    lv_obj_set_align(ui_PlaylistSelectRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_PlaylistSelectRoller, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TvVolumeSlider = lv_slider_create(ui_TabTV);
    lv_slider_set_range(ui_TvVolumeSlider, 0, 50);
    lv_slider_set_value(ui_TvVolumeSlider, 15, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_TvVolumeSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_TvVolumeSlider, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_TvVolumeSlider, 47);
    lv_obj_set_height(ui_TvVolumeSlider, 295);
    lv_obj_set_x(ui_TvVolumeSlider, 328);
    lv_obj_set_y(ui_TvVolumeSlider, 12);
    lv_obj_set_align(ui_TvVolumeSlider, LV_ALIGN_CENTER);


    ui_PlaylistUp = lv_btn_create(ui_TabTV);
    lv_obj_set_width(ui_PlaylistUp, 100);
    lv_obj_set_height(ui_PlaylistUp, 50);
    lv_obj_set_x(ui_PlaylistUp, -270);
    lv_obj_set_y(ui_PlaylistUp, -35);
    lv_obj_set_align(ui_PlaylistUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PlaylistUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PlaylistUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblPlaylistUp = lv_label_create(ui_TabTV);
    lv_obj_set_width(ui_lblPlaylistUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPlaylistUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPlaylistUp, -271);
    lv_obj_set_y(ui_lblPlaylistUp, -34);
    lv_obj_set_align(ui_lblPlaylistUp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPlaylistUp, "up");

    ui_SelectPlaylistButton = lv_btn_create(ui_TabTV);
    lv_obj_set_width(ui_SelectPlaylistButton, 100);
    lv_obj_set_height(ui_SelectPlaylistButton, 50);
    lv_obj_set_x(ui_SelectPlaylistButton, -270);
    lv_obj_set_y(ui_SelectPlaylistButton, 42);
    lv_obj_set_align(ui_SelectPlaylistButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SelectPlaylistButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SelectPlaylistButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PlaylistDown = lv_btn_create(ui_TabTV);
    lv_obj_set_width(ui_PlaylistDown, 100);
    lv_obj_set_height(ui_PlaylistDown, 50);
    lv_obj_set_x(ui_PlaylistDown, -270);
    lv_obj_set_y(ui_PlaylistDown, 122);
    lv_obj_set_align(ui_PlaylistDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PlaylistDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PlaylistDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblPlaylistDown = lv_label_create(ui_TabTV);
    lv_obj_set_width(ui_lblPlaylistDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPlaylistDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPlaylistDown, -269);
    lv_obj_set_y(ui_lblPlaylistDown, 122);
    lv_obj_set_align(ui_lblPlaylistDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPlaylistDown, "down");

    ui_lblSelectPlaylist = lv_label_create(ui_TabTV);
    lv_obj_set_width(ui_lblSelectPlaylist, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSelectPlaylist, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSelectPlaylist, -271);
    lv_obj_set_y(ui_lblSelectPlaylist, 44);
    lv_obj_set_align(ui_lblSelectPlaylist, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSelectPlaylist, "Submit");

    lv_obj_add_event_cb(ui_LightsOnSwitch, ui_event_LightsOnSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LightsDimmerSlider, ui_event_LightsDimmerSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WakeupOverrideButton, ui_event_WakeupOverrideButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TvPowerSwitch, ui_event_TvPowerSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TvVolumeSlider, ui_event_TvVolumeSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlaylistUp, ui_event_PlaylistUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SelectPlaylistButton, ui_event_SelectPlaylistButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlaylistDown, ui_event_PlaylistDown, LV_EVENT_ALL, NULL);

}
